---

- name: install postgres
  apt: name=postgresql,postgresql-contrib,python-psycopg2 state=installed

- name: configure postgres
  template: src={{ item }}.j2 dest=/etc/postgresql/{{ pgsql_version }}/main/{{ item }} owner=postgres group=postgres mode=0600
  with_items:
    - postgresql.conf
    - pg_hba.conf
  notify:
    - restart postgres

- name: set postgres user password
  postgresql_user: name=postgres password={{ postgres_users.postgres }}
  become: yes
  become_user: postgres
  become_method: sudo
